### ISSUE TITLE
Add me as a maintainer of the Teamwork_15 theme

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/teamwork_15#1]
I was interested in creating a new contrib theme with support for the color module and support for SASS (my preference is gulp). 

I see that this module appears to be unmaintained and has some of the features that I was looking for but that are out of date. Rather than start fresh, it feels like it might be better for the community if I help update this existing theme. 

Atten: @biolithic - if you would like, I can take over this module completely or if you are interested in working on it in the future, I'd be happy to help. Let me know. 

I'll check back in two weeks.

**Comment by klonos** [comment]
Enough time has been provided for the current maintainer to respond. Please go ahead @stpaultim 👍
